spring:
  datasource:
    url: jdbc:mysql://robsonproducoesdatabase.mysql.database.azure.com/robsonproducoes_db
    username: ${DB_USERNAME} 
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update
